name: Upload assets to R2 - Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove .DS_Store
        run: find . -name ".DS_Store" -delete

      - name: R2 Directory Upload
        uses: willfurstenau/r2-dir-upload@main
        with:
          accountid: ${{ secrets.CF_ACCOUNT_ID_PROD }}
          accesskeyid: ${{ secrets.CF_ACCESS_KEY_PROD }}
          secretaccesskey: ${{ secrets.CF_SECRET_KEY_PROD }}
          bucket: ${{ secrets.R2_BUCKET_PROD }}
          source: ${{ github.workspace }}/static
          destination: /
